export type ProductCategory =
  | 'BUDGETING'
  | 'CRYPTOCURRENCY'
  | 'DIVIDEND_TRACKING'
  | 'ETF_TRACKING'
  | 'FAMILY_OFFICE'
  | 'FINANCIAL_PLANNING'
  | 'INVESTMENT_RESEARCH'
  | 'NET_WORTH_TRACKING'
  | 'STOCK_TRACKING'
  | 'TAX_REPORTING'
  | 'WEALTH_MANAGEMENT';
