blank_issues_enabled: false

contact_links:
  - name: Join Ghostfolio.io on Slack
    url: https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg
    about: Join our Slack workspace to ask questions, share ideas, and connect with the community.
