export const PROPERTY_DATA_GATHERING_QUEUE_INTERVAL =
  'DATA_GATHERING_QUEUE_INTERVAL';
export const PROPERTY_API_KEY_OPENROUTER = 'API_KEY_OPENROUTER';
export const PROPERTY_OPENROUTER_MODEL = 'OPENROUTER_MODEL';
