export const PROPERTY_DATA_GATHERING_QUEUE_INTERVAL =
  'DATA_GATHERING_QUEUE_INTERVAL';
export const PROPERTY_IS_DEMO_MODE = 'IS_DEMO_MODE';
export const PROPERTY_IS_USER_SIGNUP_ENABLED = 'IS_USER_SIGNUP_ENABLED';
export const PROPERTY_MAX_PORTFOLIOS = 'MAX_PORTFOLIOS';
export const PROPERTY_MAX_USERS = 'MAX_USERS';
export const PROPERTY_API_KEY_OPENROUTER = 'API_KEY_OPENROUTER';
export const PROPERTY_OPENROUTER_MODEL = 'OPENROUTER_MODEL';
