import '@angular/localize/init';

export const paths = {
  access: 'access',
  account: 'account',
  accounts: 'accounts',
  activities: 'activities',
  adminControl: 'admin',
  allocations: 'allocations',
  api: 'api',
  auth: 'auth',
  blog: 'blog',
  demo: 'demo',
  fire: 'fire',
  holdings: 'holdings',
  home: 'home',
  i18n: 'i18n',
  jobs: 'jobs',
  market: 'market',
  marketData: 'market-data',
  membership: 'membership',
  personalFinanceTools: 'personal-finance-tools',
  portfolio: 'portfolio',
  public: 'p',
  saas: 'saas',
  settings: 'settings',
  start: 'start',
  summary: 'summary',
  users: 'users',
  watchlist: 'watchlist',
  webauthn: 'webauthn',
  xRay: 'x-ray',
  zen: 'zen',

  // Publicly accessible pages
  about: $localize`:kebab-case:about`,
  changelog: $localize`:kebab-case:changelog`,
  faq: $localize`:kebab-case:faq`,
  features: $localize`:kebab-case:features`,
  glossary: $localize`:kebab-case:glossary`,
  guides: $localize`:kebab-case:guides`,
  license: $localize`:kebab-case:license`,
  markets: $localize`:kebab-case:markets`,
  openSourceAlternativeTo: $localize`:kebab-case:open-source-alternative-to`,
  openStartup: 'open',
  ossFriends: 'oss-friends',
  pricing: $localize`:kebab-case:pricing`,
  privacyPolicy: $localize`:kebab-case:privacy-policy`,
  register: $localize`:kebab-case:register`,
  resources: $localize`:kebab-case:resources`,
  selfHosting: $localize`:kebab-case:self-hosting`,
  termsOfService: $localize`:kebab-case:terms-of-service`
};
