import { Product } from '@ghostfolio/common/interfaces';

export const personalFinanceTools: Product[] = [
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: true,
    key: 'acemoney',
    name: 'AceMoney',
    note: 'License is a perpetual license',
    origin: 'US',
    platforms: ['MACOS', 'WINDOWS'],
    pricingPerYear: '$44.95',
    slogan: 'Lifetime Personal Finance Control, One Single Payment.',
    url: 'https://www.mechcad.net'
  },
  {
    categories: ['FAMILY_OFFICE', 'WEALTH_MANAGEMENT'],
    key: 'addepar',
    name: 'Addepar',
    slogan: 'Transform your business with Addepar',
    url: 'https://addepar.com'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    key: 'akkuro',
    name: 'Akkuro',
    slogan: 'Composable Banking',
    url: 'https://akkuro.com'
  },
  {
    categories: ['ETF_TRACKING', 'STOCK_TRACKING'],
    founded: 2023,
    hasSelfHostingAbility: false,
    key: 'allinvestview',
    languages: ['English'],
    name: 'AllInvestView',
    platforms: ['WEB'],
    slogan: 'All your Investments in One View',
    url: 'https://www.allinvestview.com'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    founded: 2019,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'allvue-systems',
    name: 'Allvue Systems',
    origin: 'US',
    slogan: 'Investment Software Suite',
    url: 'https://www.allvuesystems.com'
  },
  {
    categories: [
      'BUDGETING',
      'CRYPTOCURRENCY',
      'ETF_TRACKING',
      'NET_WORTH_TRACKING',
      'STOCK_TRACKING',
      'TAX_REPORTING'
    ],
    founded: 2024,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'alpgain',
    languages: ['Deutsch', 'English', 'Français', 'Italiano'],
    name: 'Alpgain',
    origin: 'CH',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: 'CHF 99',
    slogan: 'Manage your entire Swiss wealth in one place',
    url: 'https://alpgain.ch'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2016,
    key: 'alphatrackr',
    languages: ['English'],
    name: 'AlphaTrackr',
    platforms: ['WEB'],
    slogan: 'Investment Portfolio Tracking Tool',
    url: 'https://www.alphatrackr.com'
  },
  {
    categories: ['FAMILY_OFFICE', 'NET_WORTH_TRACKING', 'WEALTH_MANAGEMENT'],
    founded: 2017,
    hasSelfHostingAbility: false,
    key: 'altoo',
    name: 'Altoo Wealth Platform',
    origin: 'CH',
    platforms: ['WEB'],
    slogan: 'Simplicity for Complex Wealth',
    url: 'https://altoo.io'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    founded: 2018,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'altruist',
    name: 'Altruist',
    origin: 'US',
    platforms: ['WEB'],
    slogan: 'The wealth platform built for independent advisors',
    url: 'https://altruist.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2023,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'amsflow',
    name: 'Amsflow Portfolio',
    origin: 'SG',
    pricingPerYear: '$228',
    slogan: 'Portfolio Visualizer',
    url: 'https://amsflow.com'
  },
  {
    categories: ['ETF_TRACKING', 'STOCK_TRACKING'],
    founded: 2025,
    hasFreePlan: true,
    key: 'anantys',
    languages: ['English', 'Français'],
    name: 'Anantys',
    origin: 'FR',
    platforms: ['WEB'],
    slogan: 'The investment copilot with no conflict of interest',
    url: 'https://anantys.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2018,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'anlage.app',
    languages: ['English'],
    name: 'Anlage.App',
    origin: 'AT',
    platforms: ['WEB'],
    pricingPerYear: '$120',
    slogan: 'Analyze and track your portfolio.',
    url: 'https://anlage.app'
  },
  {
    categories: ['FAMILY_OFFICE'],
    founded: 2022,
    hasFreePlan: false,
    key: 'asseta',
    languages: ['English'],
    name: 'Asseta',
    origin: 'US',
    platforms: ['WEB'],
    slogan: 'The Intelligent Family Office Suite',
    url: 'https://www.asseta.ai'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    founded: 2016,
    key: 'atominvest',
    name: 'Atominvest',
    origin: 'GB',
    slogan: 'Portfolio Management',
    url: 'https://www.atominvest.co'
  },
  {
    categories: ['BUDGETING'],
    founded: 2020,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'balance-pro',
    name: 'Balance Pro',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$47.99',
    slogan: 'The Smarter Way to Track Your Finances',
    url: 'https://www.balancepro.app'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'bankin',
    languages: ['English', 'Français'],
    name: 'Bankin’',
    origin: 'FR',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€39.99',
    slogan: 'L’app tout-en-1 pour mieux gérer son argent',
    url: 'https://www.bankin.com'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: false,
    hasSelfHostingAbility: true,
    key: 'banktivity',
    name: 'Banktivity',
    origin: 'US',
    platforms: ['IOS', 'MACOS'],
    pricingPerYear: '$59.99',
    slogan: 'Proactive money management app for macOS & iOS',
    url: 'https://www.banktivity.com'
  },
  {
    categories: ['BUDGETING'],
    key: 'basil-wealth',
    name: 'Basil',
    platforms: ['WEB'],
    url: 'https://basilwealth.com'
  },
  {
    founded: 2022,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'basil-finance',
    name: 'Basil Finance',
    slogan: 'The ultimate solution for tracking and managing your investments',
    url: 'https://basil.fi'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'beam',
    languages: ['Deutsch', 'English', 'Français'],
    name: 'Beam',
    origin: 'CH',
    platforms: ['ANDROID', 'IOS'],
    pricingPerYear: '$49.99',
    slogan: 'Stop guessing your net worth',
    url: 'https://www.get-beam.app'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2020,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'beanvest',
    name: 'Beanvest',
    origin: 'FR',
    platforms: ['WEB'],
    pricingPerYear: '$100',
    slogan: 'Stock Portfolio Tracker for Smart Investors',
    url: 'https://beanvest.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2022,
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'billi',
    languages: ['English'],
    name: 'Billi',
    origin: 'CA',
    platforms: ['ANDROID', 'IOS'],
    slogan: 'Be Money Mindful',
    url: 'https://billi.webflow.io'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2021,
    hasFreePlan: true,
    key: 'blossom-social',
    languages: ['English'],
    name: 'Blossom Social',
    origin: 'CA',
    platforms: ['ANDROID', 'IOS'],
    slogan: 'Real Portfolios, Trades & Market Insights',
    url: 'https://blossomsocial.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2024,
    hasSelfHostingAbility: false,
    key: 'bluebudget',
    languages: ['Deutsch', 'English', 'Français', 'Italiano'],
    name: 'BlueBudget',
    origin: 'CH',
    platforms: ['ANDROID', 'IOS'],
    slogan: 'Schweizer Budget App für einfache & smarte Budgetplanung',
    url: 'https://www.bluebudget.ch'
  },
  {
    categories: ['FINANCIAL_PLANNING'],
    founded: 2015,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'boldin',
    name: 'Boldin',
    note: 'Originally named as NewRetirement',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$144',
    slogan: 'Take control with retirement planning tools that begin with you',
    url: 'https://www.boldin.com'
  },
  {
    categories: [
      'BUDGETING',
      'CRYPTOCURRENCY',
      'NET_WORTH_TRACKING',
      'STOCK_TRACKING'
    ],
    founded: 2014,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'budgetbakers',
    languages: [
      'Čeština',
      'Deutsch',
      'English',
      'Español',
      'Français',
      'Italiano',
      'Українська',
      'עברית'
    ],
    name: 'BudgetBakers',
    origin: 'CZ',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Your Finances in One Place',
    url: 'https://budgetbakers.com'
  },
  {
    categories: ['BUDGETING'],
    key: 'budgetpulse',
    name: 'BudgetPulse',
    origin: 'US',
    platforms: ['WEB'],
    slogan: 'Giving life to your finance!',
    url: 'https://www.budgetpulse.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2007,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'buxfer',
    name: 'Buxfer',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$96',
    regions: ['Global'],
    slogan: 'Take control of your financial future',
    url: 'https://www.buxfer.com'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'capitally',
    name: 'Capitally',
    origin: 'PL',
    platforms: ['WEB'],
    pricingPerYear: '€80',
    slogan: 'Optimize your investments performance',
    url: 'https://www.mycapitally.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2022,
    isArchived: true,
    key: 'capmon',
    name: 'CapMon.org',
    note: 'CapMon.org was discontinued in 2023',
    origin: 'DE',
    platforms: ['WEB'],
    slogan: 'Next Generation Assets Tracking'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'cbonds',
    name: 'Cbonds',
    slogan: 'Financial Market Data Hub',
    url: 'https://cbonds.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'chaikin-analytics',
    name: 'Chaikin Analytics',
    slogan: 'Investing tools and research from Marc Chaikin & Team',
    url: 'https://chaikinanalytics.com'
  },
  {
    founded: 2024,
    hasFreePlan: true,
    isOpenSource: true,
    key: 'cleverbilling',
    languages: ['Español'],
    name: 'CleverBilling',
    slogan: 'Toma el control total de tus finanzas.'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    founded: 2011,
    key: 'cobalt',
    name: 'Cobalt',
    origin: 'US',
    platforms: ['WEB'],
    slogan: 'Next-Level Portfolio Monitoring',
    url: 'https://www.cobalt.pe'
  },
  {
    categories: ['CRYPTOCURRENCY'],
    founded: 2017,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'coinstats',
    name: 'CoinStats',
    origin: 'AM',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$168',
    slogan: 'Manage All Your Wallets & Exchanges From One Place',
    url: 'https://coinstats.app'
  },
  {
    categories: ['CRYPTOCURRENCY', 'TAX_REPORTING'],
    founded: 2013,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'cointracking',
    languages: ['Deutsch', 'English'],
    name: 'CoinTracking',
    origin: 'DE',
    platforms: ['WEB'],
    pricingPerYear: '$120',
    slogan: 'The leading Crypto Portfolio Tracker & Tax Calculator',
    url: 'https://cointracking.info'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    founded: 2019,
    key: 'compound-planning',
    name: 'Compound Planning',
    origin: 'US',
    platforms: ['IOS', 'WEB'],
    slogan: 'Modern Wealth & Investment Management',
    url: 'https://compoundplanning.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2019,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'copilot-money',
    name: 'Copilot Money',
    origin: 'US',
    platforms: ['IOS', 'MACOS', 'WEB'],
    pricingPerYear: '$95',
    slogan: 'Do money better with Copilot',
    url: 'https://www.copilot.money'
  },
  {
    categories: ['BUDGETING'],
    founded: 2014,
    hasFreePlan: false,
    key: 'countabout',
    name: 'CountAbout',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$9.99',
    slogan: 'Customizable and Secure Personal Finance App',
    url: 'https://countabout.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'danelfin',
    name: 'Danelfin',
    slogan: 'AI-Powered Stock Picking',
    url: 'https://danelfin.com'
  },
  {
    categories: ['FAMILY_OFFICE'],
    founded: 2023,
    hasFreePlan: false,
    key: 'danti',
    name: 'Danti',
    origin: 'GB',
    slogan: 'Digitising Generational Wealth',
    url: 'https://danti.io'
  },
  {
    categories: ['CRYPTOCURRENCY'],
    founded: 2020,
    key: 'de.fi',
    languages: ['English'],
    name: 'De.Fi',
    slogan: 'DeFi Portfolio Tracker',
    url: 'https://de.fi'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'WEALTH_MANAGEMENT'],
    key: 'deepvest',
    name: 'DeepVest',
    slogan:
      'The AI-Powered Research Platform for Financial Advisors and Investment Managers',
    url: 'https://www.deepvest.ai'
  },
  {
    categories: ['CRYPTOCURRENCY'],
    founded: 2016,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'defi-portfolio-tracker-by-zerion',
    languages: ['English'],
    name: 'DeFi Portfolio Tracker by Zerion',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$99',
    slogan: 'DeFi Portfolio Tracker for All Chains',
    url: 'https://zerion.io/defi-portfolio-tracker'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2022,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'degiro-portfolio-tracker-by-capitalyse',
    languages: ['English'],
    name: 'DEGIRO Portfolio Tracker by Capitalyse',
    origin: 'NL',
    platforms: ['WEB'],
    pricingPerYear: '€24',
    slogan: 'Democratizing Data Analytics',
    url: 'https://capitalyse.app/app/degiro'
  },
  {
    categories: ['CRYPTOCURRENCY', 'STOCK_TRACKING'],
    founded: 2017,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'delta',
    name: 'Delta Investment Tracker',
    note: 'Acquired by eToro',
    origin: 'BE',
    platforms: ['ANDROID', 'IOS', 'MACOS', 'WEB', 'WINDOWS'],
    pricingPerYear: '$150',
    slogan: 'The app to track all your investments. Make smart moves only.',
    url: 'https://delta.app'
  },
  {
    categories: ['DIVIDEND_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'digrin',
    languages: ['English'],
    name: 'Digrin',
    platforms: ['WEB'],
    pricingPerYear: '$49.90',
    slogan: 'Dividend Portfolio Tracker',
    url: 'https://www.digrin.com'
  },
  {
    categories: ['DIVIDEND_TRACKING'],
    hasFreePlan: true,
    key: 'dividend-watch',
    name: 'Dividend Watch',
    slogan: 'The Essential Dividend and Portfolio Tracker',
    url: 'https://dividend.watch'
  },
  {
    categories: ['DIVIDEND_TRACKING'],
    key: 'dividend-wealth',
    name: 'Dividend Wealth',
    slogan: 'Track Your Dividends Like a Pro',
    url: 'https://dividend-wealth.com'
  },
  {
    categories: ['DIVIDEND_TRACKING'],
    key: 'divtracker',
    name: 'DivTracker',
    slogan: 'Your Ultimate Dividend Tracker',
    url: 'https://divtracker.app'
  },
  {
    categories: ['DIVIDEND_TRACKING'],
    founded: 2019,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'divvydiary',
    languages: ['Deutsch', 'English'],
    name: 'DivvyDiary',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€65',
    slogan: 'Your personal Dividend Calendar',
    url: 'https://divvydiary.com'
  },
  {
    categories: ['CRYPTOCURRENCY', 'ETF_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'donkycapital',
    languages: ['English', 'Italiano'],
    name: 'DonkyCapital',
    origin: 'IT',
    platforms: ['ANDROID', 'WEB'],
    pricingPerYear: '€57.48',
    slogan: 'The Portfolio Tracker that replaces your spreadsheets',
    url: 'https://www.donkycapital.com'
  },
  {
    categories: ['FINANCIAL_PLANNING', 'NET_WORTH_TRACKING'],
    founded: 2009,
    hasSelfHostingAbility: false,
    key: 'empower',
    name: 'Empower',
    note: 'Originally named as Personal Capital',
    origin: 'US',
    platforms: ['WEB'],
    slogan: 'Get answers to your money questions',
    url: 'https://www.empower.com'
  },
  {
    alias: '8figures',
    categories: ['NET_WORTH_TRACKING', 'STOCK_TRACKING'],
    founded: 2022,
    key: 'eightfigures',
    name: '8FIGURES',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Portfolio Tracker Designed by Professional Investors',
    url: 'https://8figures.com'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'emma',
    languages: ['English'],
    name: 'Emma',
    origin: 'GB',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '£41.99',
    slogan: 'Take control of your money',
    url: 'https://emma-app.com'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    key: 'envestnet',
    name: 'Envestnet',
    slogan: 'Everybody Deserves Financial Wellness',
    url: 'https://www.envestnet.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    hasFreePlan: true,
    key: 'epsmomentum',
    name: 'EPS Momentum',
    origin: 'US',
    slogan: 'Stock Selection Analytics for Investors',
    url: 'https://epsmomentum.com'
  },
  {
    categories: ['ETF_TRACKING', 'INVESTMENT_RESEARCH'],
    key: 'etf-action',
    name: 'ETF Action',
    slogan: 'Markets through the lens of ETFs',
    url: 'https://www.etfaction.com'
  },
  {
    categories: ['ETF_TRACKING', 'INVESTMENT_RESEARCH'],
    key: 'etf-insider',
    name: 'ETF Insider',
    slogan: 'Precision asset allocation',
    url: 'https://etfinsider.co'
  },
  {
    categories: ['ETF_TRACKING', 'INVESTMENT_RESEARCH'],
    hasFreePlan: true,
    key: 'etf-research-center',
    name: 'ETF Research Center',
    slogan: 'A Smarter Approach to Exchange Traded Funds',
    url: 'https://www.etfrc.com'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    founded: 2010,
    hasFreePlan: false,
    key: 'etops',
    name: 'etops',
    origin: 'CH',
    platforms: ['WEB'],
    slogan: 'Your financial superpower',
    url: 'https://www.etops.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2015,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'everydollar',
    name: 'EveryDollar',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Plan, track, find more margin',
    url: 'https://www.ramseysolutions.com/money/everydollar'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    founded: 2020,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'exirio',
    name: 'Exirio',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$100',
    slogan: 'All your wealth, in one place.',
    url: 'https://www.exirio.com'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    hasFreePlan: false,
    hasSelfHostingAbility: true,
    key: 'expersoft',
    name: 'Expersoft',
    origin: 'CH',
    slogan: 'Investment Management Platforms',
    url: 'https://www.expersoft.com'
  },
  {
    categories: ['ETF_TRACKING', 'INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2008,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'extraetf',
    languages: ['Deutsch', 'English'],
    name: 'extraETF',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€89.99',
    slogan: 'Die besten ETFs finden, vergleichen und beobachten',
    url: 'https://extraetf.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'factorstoday',
    name: 'FactorsToday',
    slogan: 'Modern Quantitative Analysis',
    url: 'https://www.factorstoday.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'fast-graphs',
    name: 'FAST Graphs',
    slogan: 'Invest Intelligently with the Most Powerful Stock Analysis Tool',
    url: 'https://www.fastgraphs.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    founded: 2018,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'fey',
    name: 'Fey',
    note: 'Fey was discontinued in 2025',
    origin: 'CA',
    pricingPerYear: '$300',
    slogan: 'Make better investments.',
    url: 'https://fey.com'
  },
  {
    founded: 2023,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'fina',
    languages: ['English'],
    name: 'Fina',
    origin: 'US',
    pricingPerYear: '$115',
    slogan: 'Flexible Financial Management',
    url: 'https://www.fina.money'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    founded: 2023,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'finanzfluss-copilot',
    name: 'Finanzfluss Copilot',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€69.99',
    slogan: 'Portfolio Tracker für dein Vermögen',
    url: 'https://www.finanzfluss.de/copilot'
  },
  {
    categories: ['BUDGETING'],
    founded: 2015,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'finanzguru',
    languages: ['Deutsch'],
    name: 'Finanzguru',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'MACOS'],
    slogan: 'Finanzen. Magisch. Einfach.',
    url: 'https://www.finanzguru.de'
  },
  {
    categories: ['NET_WORTH_TRACKING', 'STOCK_TRACKING'],
    founded: 2020,
    key: 'finary',
    languages: ['Deutsch', 'English', 'Français'],
    name: 'Finary',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Real-Time Portfolio Tracker & Stock Tracker',
    url: 'https://finary.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2021,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'finateka',
    languages: ['English'],
    name: 'FINATEKA',
    origin: 'US',
    platforms: ['ANDROID', 'IOS'],
    slogan:
      'The most convenient mobile application for personal finance accounting',
    url: 'https://finateka.com'
  },
  {
    categories: ['NET_WORTH_TRACKING', 'STOCK_TRACKING'],
    founded: 2022,
    key: 'fincake',
    name: 'Fincake',
    origin: 'VG',
    slogan: 'Easy-to-use Portfolio Tracker',
    url: 'https://fincake.io'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    founded: 2015,
    hasFreePlan: false,
    key: 'fincite',
    name: 'Fincite',
    origin: 'DE',
    platforms: ['WEB'],
    slogan: 'Wealth Management Software',
    url: 'https://fincite.de'
  },
  {
    categories: ['BUDGETING'],
    hasSelfHostingAbility: false,
    key: 'fintable',
    languages: ['English'],
    name: 'Fintable',
    origin: 'CA',
    platforms: ['WEB'],
    pricingPerYear: '$84.00',
    slogan: 'Sync your bank to spreadsheets',
    url: 'https://fintable.io'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'fintel',
    name: 'Fintel',
    slogan: 'Essential Tools for Investors and Traders',
    url: 'https://fintel.io'
  },
  {
    categories: ['ETF_TRACKING', 'STOCK_TRACKING'],
    founded: 2021,
    hasSelfHostingAbility: false,
    key: 'finvest',
    name: 'Finvest',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Grow your wealth in a stress-free way',
    url: 'https://www.getfinvest.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    hasFreePlan: true,
    key: 'finviz',
    name: 'Finviz',
    slogan:
      'Stock screener for investors and traders, financial visualizations',
    url: 'https://finviz.com'
  },
  {
    categories: ['BUDGETING', 'FINANCIAL_PLANNING', 'NET_WORTH_TRACKING'],
    founded: 2023,
    hasFreePlan: true,
    key: 'finwise',
    name: 'FinWise',
    origin: 'ZA',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€69.99',
    slogan: 'Personal finances, simplified',
    url: 'https://finwiseapp.io'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    founded: 2021,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'firekit',
    languages: ['English', 'українська мова'],
    name: 'FIREkit',
    origin: 'UA',
    pricingPerYear: '$40',
    slogan: 'A simple solution to track your wealth online',
    url: 'https://firekit.space'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'fiscal.ai',
    name: 'Fiscal.ai',
    slogan: 'The Modern Financial Data Platform',
    url: 'https://fiscal.ai'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'flow',
    languages: ['English', 'Nederlands'],
    name: 'Flow',
    origin: 'NL',
    platforms: ['ANDROID', 'IOS'],
    pricingPerYear: '€23.88',
    slogan: 'Your money on autopilot',
    url: 'https://flowyour.money'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'folishare',
    languages: ['Deutsch', 'English'],
    name: 'folishare',
    origin: 'AT',
    pricingPerYear: '$65',
    slogan: 'Take control over your investments',
    url: 'https://www.folishare.com'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'frollo',
    languages: ['English'],
    name: 'Frollo',
    origin: 'AU',
    platforms: ['ANDROID', 'IOS'],
    slogan: 'Feel good about money',
    url: 'https://www.frollo.com.au'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 1993,
    hasSelfHostingAbility: true,
    key: 'fund-manager',
    name: 'Fund Manager',
    note: 'License is a perpetual license',
    origin: 'US',
    platforms: ['WINDOWS'],
    pricingPerYear: '$99',
    slogan: 'Powerful portfolio management software',
    url: 'https://www.fundmanagersoftware.com'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'gasti',
    languages: [
      'Deutsch',
      'English',
      'Español',
      'Français',
      'Italiano',
      'Português'
    ],
    name: 'Gasti',
    origin: 'AR',
    platforms: ['WEB'],
    pricingPerYear: '$60',
    regions: ['Global'],
    slogan: 'Take control of your finances from WhatsApp',
    url: 'https://gasti.pro'
  },
  {
    categories: ['NET_WORTH_TRACKING', 'STOCK_TRACKING'],
    founded: 2020,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'getquin',
    languages: ['Deutsch', 'English'],
    name: 'getquin',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€48',
    slogan: 'Portfolio Tracker, Analysis & Community',
    url: 'https://www.getquin.com'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'goodbudget',
    name: 'Goodbudget',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Budget with a why',
    url: 'https://goodbudget.com'
  },
  {
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'gospatz',
    name: 'goSPATZ',
    note: 'Renamed to Money Peak',
    origin: 'DE',
    slogan: 'Volle Kontrolle über deine Investitionen'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'gurufocus',
    name: 'GuruFocus',
    slogan: 'Stock Market Research, Data and Tools',
    url: 'https://www.gurufocus.com'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING'],
    founded: 2024,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'gustav',
    languages: ['Français'],
    name: 'Gustav',
    origin: 'FR',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€59.99',
    slogan: 'Prenez enfin le contrôle de votre argent',
    url: 'https://get-gustav.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'hedgefollow',
    name: 'HedgeFollow',
    slogan: 'Follow Hedge Funds & Insiders using 13F filings',
    url: 'https://hedgefollow.com'
  },
  {
    categories: ['DIVIDEND_TRACKING', 'ETF_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'helvestor',
    languages: ['Deutsch'],
    name: 'Helvestor',
    origin: 'CH',
    platforms: ['IOS', 'WEB'],
    slogan: 'Dein Vermögen im Überblick',
    url: 'https://www.helvestor.ch'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'holistic-capital',
    languages: ['Deutsch'],
    name: 'Holistic',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Die All-in-One Lösung für dein Vermögen.',
    url: 'https://holistic.capital',
    useAnonymously: true
  },
  {
    categories: ['BUDGETING'],
    founded: 2017,
    hasSelfHostingAbility: false,
    key: 'honeydue',
    name: 'Honeydue',
    origin: 'US',
    platforms: ['ANDROID', 'IOS'],
    slogan: 'Finance App for Couples',
    url: 'https://www.honeydue.com'
  },
  {
    founded: 2003,
    hasSelfHostingAbility: true,
    isArchived: true,
    key: 'ibank',
    name: 'iBank',
    note: 'Renamed to Banktivity',
    origin: 'US'
  },
  {
    founded: 2022,
    key: 'income-reign',
    languages: ['English'],
    name: 'Income Reign',
    note: 'Income Reign was discontinued in 2025',
    origin: 'US',
    pricingPerYear: '$120'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    hasFreePlan: true,
    key: 'insidearbitrage',
    name: 'InsideArbitrage',
    url: 'https://www.insidearbitrage.com'
  },
  {
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'intuit-mint',
    name: 'Intuit Mint',
    note: 'Intuit Mint was discontinued in 2023',
    origin: 'US',
    pricingPerYear: '$60',
    slogan: 'Managing money, made simple'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'invesst',
    name: 'Invesst',
    slogan: 'Power Your Portfolio with AI',
    url: 'https://invesst.ai'
  },
  {
    categories: ['STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'investify',
    name: 'Investify',
    origin: 'PK',
    platforms: ['ANDROID', 'IOS'],
    slogan: 'Advanced portfolio tracking and stock market information',
    url: 'https://www.investify.pk'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    founded: 2021,
    hasFreePlan: true,
    hasSelfHostingAbility: true,
    key: 'invmon',
    name: 'InvMon',
    note: 'Originally named as A2PB',
    origin: 'CH',
    platforms: ['MACOS'],
    pricingPerYear: '$156',
    slogan: 'Track all your assets, investments and portfolios in one place',
    url: 'https://invmon.com',
    useAnonymously: true
  },
  {
    categories: ['CRYPTOCURRENCY', 'ETF_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'inwestuje',
    languages: ['Polski'],
    name: 'inwestuje.app',
    origin: 'PL',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Inwestujesz? Śledź swój majątek w jednym miejscu',
    url: 'https://inwestuje.app'
  },
  {
    categories: ['ETF_TRACKING'],
    founded: 2011,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'justetf',
    name: 'justETF',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€119',
    slogan: 'ETF portfolios made simple',
    url: 'https://www.justetf.com'
  },
  {
    categories: ['CRYPTOCURRENCY', 'TAX_REPORTING'],
    founded: 2018,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'koinly',
    name: 'Koinly',
    origin: 'SG',
    slogan: 'Track all your crypto wallets in one place',
    url: 'https://koinly.io'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    founded: 2016,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'koyfin',
    name: 'Koyfin',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$468',
    slogan: 'Comprehensive financial data analysis',
    url: 'https://www.koyfin.com'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    founded: 2019,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'kubera',
    name: 'Kubera®',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$249',
    slogan: 'The Time Machine for your Net Worth',
    url: 'https://www.kubera.com'
  },
  {
    categories: [
      'CRYPTOCURRENCY',
      'ETF_TRACKING',
      'INVESTMENT_RESEARCH',
      'STOCK_TRACKING'
    ],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'kyro',
    languages: ['English'],
    name: 'Kyro',
    platforms: ['WEB'],
    url: 'https://my.kyro.app'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    founded: 2021,
    hasFreePlan: false,
    key: 'leafs',
    languages: ['Deutsch', 'English'],
    name: 'Leafs',
    origin: 'CH',
    slogan: 'Sustainability insights for wealth managers',
    url: 'https://leafs.ch'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'lumio',
    languages: ['English'],
    name: 'Lumio',
    origin: 'GB',
    platforms: ['ANDROID', 'IOS'],
    pricingPerYear: '£26.99',
    slogan: 'Couples finances, made easy',
    url: 'https://www.lumio-app.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2020,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'lunch-money',
    name: 'Lunch Money',
    origin: 'CA',
    slogan: 'Delightfully simple personal finance and budgeting',
    url: 'https://lunchmoney.app'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    founded: 2018,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'magnifi',
    name: 'Magnifi',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$132',
    slogan: 'AI Investing Assistant',
    url: 'https://magnifi.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'marketinout',
    name: 'MarketInOut',
    slogan: 'Stock Screener with Backtesting & Advanced Filters',
    url: 'https://www.marketinout.com'
  },
  {
    categories: ['ETF_TRACKING', 'STOCK_TRACKING'],
    key: 'marketlog',
    name: 'Marketlog',
    slogan: 'Stock Portfolio and Investments Tracker',
    url: 'https://www.marketlog.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    founded: 2022,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'markets.sh',
    languages: ['English'],
    name: 'markets.sh',
    origin: 'DE',
    platforms: ['WEB'],
    pricingPerYear: '€168',
    regions: ['Global'],
    slogan: 'Financial Intelligence Platform',
    url: 'https://markets.sh'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'marketscreener',
    name: 'MarketScreener',
    slogan: 'Financial News & Stock Market Quotes',
    url: 'https://www.marketscreener.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'marketxls',
    name: 'MarketXLS',
    slogan: 'Real-Time Stock Data & Analysis in Excel',
    url: 'https://marketxls.com'
  },
  {
    categories: ['FAMILY_OFFICE', 'WEALTH_MANAGEMENT'],
    founded: 2010,
    key: 'masttro',
    name: 'Masttro',
    origin: 'US',
    slogan: 'Your platform for wealth in full view',
    url: 'https://masttro.com'
  },
  {
    founded: 2021,
    hasFreePlan: false,
    hasSelfHostingAbility: true,
    isArchived: true,
    isOpenSource: true,
    key: 'maybe-finance',
    languages: ['English'],
    name: 'Maybe Finance',
    note: 'Maybe Finance was discontinued in 2023, relaunched in 2024, and discontinued again in 2025',
    origin: 'US',
    pricingPerYear: '$145',
    regions: ['US'],
    slogan: 'Your financial future, in your control',
    url: 'https://github.com/maybe-finance/maybe'
  },
  {
    categories: ['CRYPTOCURRENCY'],
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'merlincrypto',
    languages: ['English'],
    name: 'Merlin',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$204',
    regions: ['CA', 'US'],
    slogan: 'The smartest way to track your crypto',
    url: 'https://www.merlincrypto.com'
  },
  {
    categories: ['FINANCIAL_PLANNING'],
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'mezzi',
    name: 'Mezzi',
    origin: 'US',
    platforms: ['IOS', 'WEB'],
    pricingPerYear: '$48',
    slogan: 'Self-manage your wealth. Get fiduciary advice.',
    url: 'https://www.mezzi.com'
  },
  {
    founded: 1991,
    hasSelfHostingAbility: true,
    isArchived: true,
    key: 'microsoft-money',
    name: 'Microsoft Money',
    note: 'Microsoft Money was discontinued in 2010',
    origin: 'US'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'moatmap',
    name: 'MoatMap',
    slogan: 'AI Stock Screening & Equity Research',
    url: 'https://moatmap.ai'
  },
  {
    categories: ['BUDGETING'],
    founded: 2019,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'monarch-money',
    name: 'Monarch Money',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$99.99',
    slogan: 'The modern way to manage your money',
    url: 'https://www.monarch.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 1999,
    hasFreePlan: false,
    hasSelfHostingAbility: true,
    key: 'moneydance',
    name: 'Moneydance',
    origin: 'GB',
    platforms: ['ANDROID', 'IOS', 'LINUX', 'MACOS', 'WINDOWS'],
    pricingPerYear: '$100',
    slogan: 'Personal Finance Manager for Mac, Windows, and Linux',
    url: 'https://moneydance.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2016,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'moneypatrol',
    name: 'MoneyPatrol',
    origin: 'US',
    pricingPerYear: '$29.99',
    slogan: 'Personal Accounting Made Easy, Accurate, Comprehensive',
    url: 'https://www.moneypatrol.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'moneypeak',
    name: 'Money Peak',
    note: 'Originally named as goSPATZ',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Dein smarter Finance Assistant',
    url: 'https://moneypeak.ai'
  },
  {
    categories: ['BUDGETING'],
    founded: 2007,
    key: 'moneyspire',
    name: 'Moneyspire',
    note: 'License is a perpetual license',
    origin: 'US',
    platforms: ['LINUX', 'MACOS', 'WINDOWS'],
    pricingPerYear: '$59.99',
    slogan: 'Have total control of your financial life',
    url: 'https://www.moneyspire.com'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: true,
    key: 'moneywell',
    name: 'MoneyWell',
    origin: 'US',
    platforms: ['IOS', 'MACOS'],
    slogan: 'Personal Budgeting Software for Mac and iOS',
    url: 'https://moneywell.app'
  },
  {
    categories: ['BUDGETING'],
    key: 'moneywiz',
    name: 'MoneyWiz',
    origin: 'US',
    platforms: ['IOS', 'MACOS'],
    pricingPerYear: '$29.99',
    slogan: 'Get money management superpowers',
    url: 'https://www.wiz.money'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'monse',
    name: 'Monse',
    note: 'Renamed to Nexafin',
    pricingPerYear: '$60',
    slogan: 'Gain financial control and keep your data private.',
    url: 'https://monse.app'
  },
  {
    categories: ['BUDGETING'],
    founded: 2025,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'monsy',
    languages: ['English'],
    name: 'Monsy',
    origin: 'ID',
    platforms: ['WEB'],
    pricingPerYear: '$20',
    slogan: 'Smart, simple, stress-free money tracking.',
    url: 'https://www.monsy.app'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'morningstar-portfolio-manager',
    languages: ['English'],
    name: 'Morningstar® Portfolio Manager',
    origin: 'US',
    platforms: ['WEB'],
    slogan:
      'Track your equity, fund, investment trust, ETF and pension investments in one place.',
    url: 'https://www.morningstar.com/mm'
  },
  {
    categories: ['CRYPTOCURRENCY', 'ETF_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    key: 'my-stocks-portfolio',
    languages: [
      'Deutsch',
      'English',
      'Français',
      'Türkçe',
      '简体中文',
      '繁體中文'
    ],
    name: 'My Stocks Portfolio & Market',
    platforms: ['ANDROID', 'IOS'],
    pricingPerYear: '$49.99',
    slogan: 'Keep track of and visualize your investments throughout your day',
    url: 'https://peeksoft.co'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'myfinancetools',
    languages: ['Deutsch', 'English', 'Español', 'Français', 'Português'],
    name: 'MyFinanceTools',
    platforms: ['WEB'],
    pricingPerYear: '$36',
    slogan: 'Your Personal Finance Command Center',
    url: 'https://myfinancetools.io'
  },
  {
    categories: ['CRYPTOCURRENCY', 'NET_WORTH_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'myfund',
    languages: ['English', 'Polski'],
    name: 'MyFund',
    origin: 'PL',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: 'PLN 36.10',
    slogan: 'Manage all your assets and accounts in one place',
    url: 'https://myfund.pl'
  },
  {
    categories: ['CRYPTOCURRENCY'],
    founded: 2020,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'nansen',
    name: 'Crypto Portfolio Tracker by Nansen',
    origin: 'SG',
    platforms: ['WEB'],
    pricingPerYear: '$1188',
    slogan: 'Your Complete Crypto Portfolio, Reimagined',
    url: 'https://www.nansen.ai/crypto-portfolio-tracker'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2017,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'navexa',
    name: 'Navexa',
    origin: 'AU',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$90',
    slogan: 'The Intelligent Portfolio Tracker',
    url: 'https://www.navexa.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'networthy',
    name: 'Networthy',
    platforms: ['WEB'],
    pricingPerYear: '€49.99',
    slogan: 'Your Personal Financial Analyst, powered by AI.',
    url: 'https://networthy.pro'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    key: 'nexafin',
    name: 'Nexafin',
    platforms: ['WEB'],
    slogan: 'Your Finances. Finally Clear.',
    url: 'https://nexafin.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'okama',
    name: 'okama',
    slogan: 'Efficient Frontier for the investment portfolios',
    url: 'https://okama.io'
  },
  {
    categories: ['DIVIDEND_TRACKING'],
    hasFreePlan: true,
    key: 'onlydividends',
    languages: ['English', 'Español', 'Français'],
    name: 'OnlyDividends',
    origin: 'FR',
    platforms: ['ANDROID', 'IOS'],
    pricingPerYear: '€49.99',
    slogan: 'Dividend Day Should Feel Like Payday',
    url: 'https://onlydividends.app'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    founded: 2020,
    hasSelfHostingAbility: false,
    hasFreePlan: true,
    key: 'parqet',
    name: 'Parqet',
    note: 'Originally named as Tresor One',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '€99.99',
    regions: ['AT', 'CH', 'DE'],
    slogan: 'Dein Vermögen immer im Blick',
    url: 'https://www.parqet.com'
  },
  {
    categories: ['FINANCIAL_PLANNING', 'STOCK_TRACKING'],
    founded: 2017,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'passiv',
    languages: ['English'],
    name: 'Passiv',
    origin: 'CA',
    platforms: ['WEB'],
    pricingPerYear: '$99',
    slogan: 'Autopilot for your Portfolio',
    url: 'https://passiv.com'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'patrice',
    languages: [
      'Deutsch',
      'English',
      'Español',
      'Français',
      'Italiano',
      'Português'
    ],
    name: 'Patrice',
    platforms: ['WEB'],
    pricingPerYear: '€49',
    slogan: 'Votre patrimoine, enfin clair',
    url: 'https://mypatrice.com'
  },
  {
    categories: ['BUDGETING'],
    hasSelfHostingAbility: false,
    key: 'peek',
    name: 'Peek',
    origin: 'SG',
    platforms: ['IOS'],
    slogan: 'Feel in control of your money without spreadsheets or shame',
    url: 'https://peek.money'
  },
  {
    categories: ['BUDGETING'],
    key: 'pennies',
    name: 'Pennies',
    origin: 'US',
    platforms: ['IOS'],
    pricingPerYear: '$39.99',
    slogan: 'Your money. Made simple.',
    url: 'https://www.getpennies.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2022,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'pinklion',
    name: 'PinkLion',
    origin: 'DE',
    platforms: ['WEB'],
    pricingPerYear: '€50',
    slogan: 'Invest smarter, not harder',
    url: 'https://pinklion.xyz'
  },
  {
    categories: ['DIVIDEND_TRACKING'],
    founded: 2023,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'plainzer',
    languages: ['English'],
    name: 'Plainzer',
    origin: 'PL',
    pricingPerYear: '$74',
    slogan: 'Free dividend tracker for your portfolio',
    url: 'https://plainzer.com'
  },
  {
    categories: ['FINANCIAL_PLANNING', 'NET_WORTH_TRACKING'],
    founded: 2023,
    hasSelfHostingAbility: false,
    key: 'plannix',
    name: 'Plannix',
    origin: 'IT',
    platforms: ['WEB'],
    slogan: 'Your Personal Finance Hub',
    url: 'https://www.plannix.co'
  },
  {
    categories: ['BUDGETING'],
    founded: 2015,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'pocketguard',
    name: 'PocketGuard',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$74.99',
    slogan: 'Budgeting App & Finance Planner',
    url: 'https://pocketguard.com'
  },
  {
    categories: ['BUDGETING', 'FINANCIAL_PLANNING'],
    founded: 2008,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'pocketsmith',
    languages: ['English'],
    name: 'PocketSmith',
    origin: 'NZ',
    platforms: ['WEB'],
    pricingPerYear: '$120',
    regions: ['Global'],
    slogan: 'Know where your money is going',
    url: 'https://www.pocketsmith.com'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'portfeo',
    languages: ['Polski'],
    name: 'Portfeo',
    origin: 'PL',
    platforms: ['WEB'],
    pricingPerYear: 'PLN 168',
    slogan: 'Wszystkie Twoje inwestycje w jednym miejscu',
    url: 'https://www.portfeo.pl'
  },
  {
    categories: ['FINANCIAL_PLANNING', 'NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'portfolio-coach',
    languages: ['English'],
    name: 'Portfolio Coach',
    origin: 'GB',
    platforms: ['WEB'],
    pricingPerYear: '£120',
    slogan: 'Know your wealth. Ask it anything.',
    url: 'https://portfoliocoach.co.uk'
  },
  {
    categories: ['DIVIDEND_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'portfolio-dividend-tracker',
    languages: ['English', 'Nederlands'],
    name: 'Portfolio Dividend Tracker',
    origin: 'NL',
    platforms: ['WEB'],
    pricingPerYear: '€60',
    slogan: 'Manage all your portfolios',
    url: 'https://portfoliodividendtracker.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'portfolio-trader',
    languages: ['English'],
    name: 'Portfolio Trader',
    origin: 'AU',
    platforms: ['IOS'],
    slogan:
      'Professional stock portfolio tracking for iPhone, iPad and Apple Watch',
    url: 'https://www.iportfoliotrader.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'portfolio-visualizer',
    languages: ['English'],
    name: 'Portfolio Visualizer',
    pricingPerYear: '$360',
    slogan: 'Tools for Better Investors',
    url: 'https://www.portfoliovisualizer.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'portfolio123',
    name: 'Portfolio123',
    slogan: 'Power Your Portfolio with Backtested Stock Strategies',
    url: 'https://www.portfolio123.com'
  },
  {
    categories: ['DIVIDEND_TRACKING', 'ETF_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'portfolioglance',
    languages: ['English', 'Polski'],
    name: 'PortfolioGlance',
    origin: 'PL',
    platforms: ['WEB'],
    slogan: 'One look. Clear picture of your portfolio.',
    url: 'https://www.portfolioglance.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'portfolioslab',
    name: 'PortfoliosLab',
    slogan: 'Financial tools for smart investors',
    url: 'https://portfolioslab.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    hasFreePlan: true,
    isArchived: true,
    key: 'portfoloo',
    name: 'Portfoloo',
    note: 'Portfoloo was discontinued',
    slogan:
      'Free Stock Portfolio Tracker with unlimited portfolio and stocks for DIY investors'
  },
  {
    categories: ['DIVIDEND_TRACKING', 'STOCK_TRACKING'],
    founded: 2021,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'portseido',
    languages: ['Deutsch', 'English', 'Français', 'Nederlands'],
    name: 'Portseido',
    origin: 'TH',
    pricingPerYear: '$96',
    slogan: 'Portfolio Performance and Dividend Tracker',
    url: 'https://www.portseido.com'
  },
  {
    categories: ['FINANCIAL_PLANNING'],
    founded: 2021,
    hasFreePlan: true,
    hasSelfHostingAbility: true,
    key: 'projectionlab',
    name: 'ProjectionLab',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$108',
    slogan: 'Build Financial Plans You Love.',
    url: 'https://projectionlab.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2022,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'prostocktracker',
    name: 'Pro Stock Tracker',
    origin: 'GB',
    platforms: ['WEB'],
    pricingPerYear: '$60',
    slogan: 'The stock portfolio tracker built for long-term investors',
    url: 'https://prostocktracker.com'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    hasSelfHostingAbility: false,
    key: 'quantive',
    name: 'Quantive',
    platforms: ['WEB'],
    slogan: 'See your financial life clearly',
    url: 'https://usequantive.app'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'rallies',
    languages: ['English'],
    name: 'Rallies',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$99.99',
    slogan:
      'Your entire financial life in one app, monitored continuously by agents',
    url: 'https://rallies.ai'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'reflexivity',
    name: 'Reflexivity',
    slogan: 'Faster Insights. Better Analysis. Greater Confidence.',
    url: 'https://reflexivity.com'
  },
  {
    categories: ['DIVIDEND_TRACKING', 'NET_WORTH_TRACKING', 'STOCK_TRACKING'],
    founded: 2014,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'rentablo',
    languages: ['Deutsch'],
    name: 'Rentablo',
    origin: 'DE',
    platforms: ['WEB'],
    slogan: 'Das kostenfreie Tool für Ihren Finanzerfolg',
    url: 'https://www.rentablo.de'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING'],
    founded: 2015,
    hasSelfHostingAbility: false,
    key: 'rocket-money',
    name: 'Rocket Money',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Track your net worth',
    url: 'https://www.rocketmoney.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2019,
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'sarmaaya.pk',
    name: 'Sarmaaya.pk Portfolio Tracking',
    note: 'Sarmaaya.pk Portfolio Tracking was discontinued in 2024',
    origin: 'PK',
    slogan: 'Unified platform for financial research and portfolio tracking'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    founded: 2004,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'seeking-alpha',
    name: 'Seeking Alpha',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$239',
    slogan: 'Stock Market Analysis & Tools for Investors',
    url: 'https://seekingalpha.com'
  },
  {
    categories: ['FINANCIAL_PLANNING', 'NET_WORTH_TRACKING'],
    founded: 2022,
    key: 'segmio',
    name: 'Segmio',
    origin: 'RO',
    platforms: ['WEB'],
    slogan: 'Track your net worth. Project every possible future.',
    url: 'https://www.segmio.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    key: 'sharescope',
    name: 'ShareScope',
    origin: 'GB',
    slogan: 'Award-winning investment, trading and portfolio management tools',
    url: 'https://www.sharescope.co.uk'
  },
  {
    categories: ['STOCK_TRACKING', 'TAX_REPORTING'],
    founded: 2007,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'sharesight',
    name: 'Sharesight',
    origin: 'NZ',
    platforms: ['WEB'],
    pricingPerYear: '$135',
    regions: ['Global'],
    slogan: 'Stock Portfolio Tracker',
    url: 'https://www.sharesight.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    hasFreePlan: true,
    isArchived: true,
    key: 'sharesmaster',
    name: 'SharesMaster',
    note: 'SharesMaster was discontinued',
    slogan: 'Free Stock Portfolio Tracker'
  },
  {
    categories: ['STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'simple-portfolio',
    name: 'Simple Portfolio',
    origin: 'CZ',
    platforms: ['WEB'],
    pricingPerYear: '€80',
    slogan: 'Stock Portfolio Tracker',
    url: 'https://simpleportfolio.app'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING'],
    founded: 2020,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'simplifi',
    name: 'Simplifi by Quicken',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    url: 'https://www.quicken.com/products/simplifi'
  },
  {
    categories: ['DIVIDEND_TRACKING', 'INVESTMENT_RESEARCH'],
    key: 'simply-safe-dividends',
    name: 'Simply Safe Dividends',
    slogan: 'Proven dividend research and tracking tools',
    url: 'https://www.simplysafedividends.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2014,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'simply-wallstreet',
    name: 'Stock Portfolio Tracker & Visualizer by Simply Wall St',
    origin: 'AU',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$120',
    slogan: 'Smart portfolio tracker for informed investors',
    url: 'https://simplywall.st'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'snoop',
    languages: ['English'],
    name: 'Snoop',
    origin: 'GB',
    platforms: ['ANDROID', 'IOS'],
    pricingPerYear: '£47.99',
    slogan: 'Cut the cost of living and build your savings',
    url: 'https://snoop.app'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2021,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'snowball-analytics',
    name: 'Snowball Analytics',
    origin: 'FR',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$80',
    slogan: 'Simple and powerful portfolio tracker',
    url: 'https://snowball-analytics.com'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'spendee',
    languages: ['English'],
    name: 'Spendee',
    origin: 'CZ',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$14.99',
    slogan: 'The only app that gets your money into shape',
    url: 'https://www.spendee.com'
  },
  {
    key: 'splashmoney',
    name: 'SplashMoney',
    origin: 'US',
    slogan: 'Manage your money anytime, anywhere.'
  },
  {
    categories: ['WEALTH_MANAGEMENT'],
    key: 'ssc-black-diamond',
    name: 'SS&C Black Diamond Wealth Solutions',
    slogan: 'The Cornerstone of a Successful Business',
    url: 'https://www.sscblackdiamond.com'
  },
  {
    categories: ['ETF_TRACKING', 'STOCK_TRACKING'],
    key: 'statfolio',
    name: 'Statfolio',
    slogan: 'Take control of your investments',
    url: 'https://statfolio.net'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    hasFreePlan: true,
    key: 'stock-analysis',
    name: 'Stock Analysis',
    slogan: 'Free Online Stock Information for Investors',
    url: 'https://stockanalysis.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2019,
    hasSelfHostingAbility: false,
    key: 'stock-events',
    name: 'Stock Events',
    origin: 'DE',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    slogan: 'Track all your Investments',
    url: 'https://stockevents.app'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'stockcharts',
    name: 'StockCharts',
    slogan: 'Advanced Charting, Screening & Financial Analysis Tools',
    url: 'https://stockcharts.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    key: 'stockle',
    name: 'Stockle',
    origin: 'FI',
    platforms: ['WEB'],
    slogan: 'Supercharge your investments tracking experience',
    url: 'https://stockle.app'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2008,
    isArchived: true,
    key: 'stockmarketeye',
    name: 'StockMarketEye',
    origin: 'FR',
    note: 'StockMarketEye was discontinued in 2023',
    slogan: 'A Powerful Portfolio & Investment Tracking App'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'stockopedia',
    name: 'Stockopedia',
    slogan: 'Data-Driven Stock Research for Active Investors',
    url: 'https://www.stockopedia.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2011,
    hasFreePlan: true,
    key: 'stock-rover',
    languages: ['English'],
    name: 'Stock Rover',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$79.99',
    slogan: 'Investment Research and Portfolio Management',
    url: 'https://www.stockrover.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    key: 'stock-unlock',
    name: 'Stock Unlock',
    slogan: 'Unique Stock Insights & Portfolio Tracking',
    url: 'https://stockunlock.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'stonksfolio',
    languages: ['English'],
    name: 'Stonksfolio',
    origin: 'BG',
    platforms: ['WEB'],
    pricingPerYear: '€49.90',
    slogan: 'Visualize all of your portfolios',
    url: 'https://stonksfolio.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'streamxls',
    name: 'StreamXLS',
    slogan: 'Excel bridge to IBKR TWS',
    url: 'https://streamxls.com'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'sumio',
    name: 'Sumio',
    origin: 'CZ',
    platforms: ['ANDROID', 'IOS'],
    pricingPerYear: '$20',
    slogan: 'AI-Powered Portfolio & Net Worth Tracker',
    url: 'https://www.sumio.app'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'tc2000',
    name: 'TC2000',
    slogan: 'Helping traders think for themselves for over 30 years',
    url: 'https://www.tc2000.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'tickeron',
    name: 'Tickeron',
    slogan: 'AI Trading Agents, Tools and News',
    url: 'https://tickeron.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    key: 'tickertape',
    name: 'Tickertape',
    slogan: 'Financial freedom begins here',
    url: 'https://www.tickertape.in'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    hasFreePlan: true,
    key: 'tikr',
    name: 'TIKR',
    slogan: 'Invest like Wall Street with TIKR Terminal',
    url: 'https://www.tikr.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2016,
    hasFreePlan: false,
    key: 'tiller',
    name: 'Tiller',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$79',
    slogan:
      'Your financial life in a spreadsheet, automatically updated each day',
    url: 'https://tiller.com'
  },
  {
    categories: ['CRYPTOCURRENCY', 'DIVIDEND_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'tinywallet',
    languages: ['Deutsch', 'English'],
    name: 'TinyWallet',
    origin: 'DE',
    platforms: ['WEB'],
    pricingPerYear: '€35',
    slogan: 'Your key to empowered wealth management',
    url: 'https://www.tinywallet.de'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'tipranks',
    name: 'TipRanks',
    slogan: 'Make Smarter, Data-Driven Investment Decisions',
    url: 'https://www.tipranks.com'
  },
  {
    categories: ['BUDGETING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'todays-budget',
    languages: ['Deutsch', 'English', 'Español', 'Français', '日本語'],
    name: 'Today’s Budget',
    origin: 'DE',
    platforms: ['IOS'],
    pricingPerYear: '$24.99',
    slogan: 'Make your money go further with daily budgets',
    url: 'https://www.todays-budget.com'
  },
  {
    categories: ['ETF_TRACKING'],
    founded: 2016,
    key: 'trackinsight',
    name: 'Trackinsight',
    slogan: 'Empowering ETF Investors',
    url: 'https://www.trackinsight.com'
  },
  {
    categories: ['DIVIDEND_TRACKING', 'ETF_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'trackinv',
    languages: ['English'],
    name: 'TrackinV',
    platforms: ['WEB'],
    pricingPerYear: '€40',
    slogan: 'See your real investment performance — across every broker',
    url: 'https://trackinv.com'
  },
  {
    categories: ['DIVIDEND_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'trackyourdividends',
    languages: ['English'],
    name: 'TrackYourDividends',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$99.99',
    slogan:
      'Follow the Performance, Payments, and Diversification of Your Dividend Portfolio',
    url: 'https://www.trackyourdividends.com'
  },
  {
    key: 'tradebb',
    name: 'TradeBB',
    slogan:
      'Trading journal for tracking, reviewing, and improving your trades',
    url: 'https://www.tradebb.ai'
  },
  {
    categories: ['TAX_REPORTING'],
    key: 'tradelog',
    name: 'TradeLog',
    regions: ['US'],
    slogan: 'Take Control Of Trader Taxes',
    url: 'https://tradelog.com'
  },
  {
    founded: 2011,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'tradervue',
    name: 'Tradervue',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$360',
    slogan: 'The Trading Journal to Improve Your Trading Performance',
    url: 'https://www.tradervue.com'
  },
  {
    key: 'tradezella',
    name: 'TradeZella',
    slogan: 'Meet Your AI Trading Partner',
    url: 'https://www.tradezella.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    hasFreePlan: true,
    key: 'tradingview',
    name: 'TradingView',
    slogan: 'Track All Markets',
    url: 'https://www.tradingview.com'
  },
  {
    categories: ['CRYPTOCURRENCY', 'ETF_TRACKING', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'treestep',
    languages: ['English', 'Français'],
    name: 'Treestep',
    origin: 'FR',
    platforms: ['WEB'],
    pricingPerYear: '€80.04',
    slogan: 'Investing that never bores you',
    url: 'https://www.treestep.fr'
  },
  {
    categories: ['STOCK_TRACKING', 'TAX_REPORTING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'trefolio',
    languages: [
      'Deutsch',
      'English',
      'Español',
      'Français',
      'Italiano',
      'Nederlands',
      'Polski',
      'Português'
    ],
    name: 'trefolio',
    platforms: ['WEB'],
    pricingPerYear: '€60',
    slogan: 'The Extra Leaf for Your Portfolio',
    url: 'https://trefolio.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'trendlyne',
    name: 'Trendlyne',
    slogan: 'The Stock Market Platform to Stay Ahead',
    url: 'https://trendlyne.com'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    founded: 2020,
    hasSelfHostingAbility: false,
    hasFreePlan: true,
    isArchived: true,
    key: 'tresor-one',
    name: 'Tresor One',
    note: 'Renamed to Parqet',
    origin: 'DE',
    regions: ['AT', 'CH', 'DE'],
    slogan: 'Dein Vermögen immer im Blick'
  },
  {
    categories: ['NET_WORTH_TRACKING', 'STOCK_TRACKING'],
    founded: 2025,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'turbobulls',
    name: 'Turbobulls',
    origin: 'RO',
    platforms: ['WEB'],
    pricingPerYear: '€39.99',
    slogan: 'Your complete financial dashboard. Actually private.',
    url: 'https://www.turbobulls.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'tweenvest',
    name: 'Tweenvest',
    slogan: 'Analyzing stocks has never been easier',
    url: 'https://www.tweenvest.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'uncle-stock',
    name: 'Uncle Stock',
    slogan: 'Fundamental Stock Screener',
    url: 'https://www.unclestock.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'utluna',
    languages: ['Deutsch', 'English', 'Français'],
    name: 'Utluna',
    origin: 'CH',
    platforms: ['WEB'],
    pricingPerYear: '$300',
    slogan: 'Your Portfolio. Revealed.',
    url: 'https://www.utluna.com',
    useAnonymously: true
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'validea',
    name: 'Validea',
    slogan:
      'Factor-Based Portfolios and Investment Research Utilizing Proven Long-Term Strategies',
    url: 'https://www.validea.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'valuedge',
    name: 'ValuEdge',
    platforms: ['WEB'],
    pricingPerYear: '€78',
    slogan: 'Track your real portfolio. Not a watchlist.',
    url: 'https://valuedge.app'
  },
  {
    categories: ['FAMILY_OFFICE', 'WEALTH_MANAGEMENT'],
    founded: 2020,
    hasFreePlan: true,
    key: 'vyzer',
    name: 'Vyzer',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$348',
    slogan: 'Virtual Family Office for Smart Wealth Management',
    url: 'https://vyzer.co'
  },
  {
    categories: ['BUDGETING', 'NET_WORTH_TRACKING'],
    founded: 2020,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'walletguide',
    name: 'Walletguide',
    origin: 'DE',
    platforms: ['WEB'],
    pricingPerYear: '€90',
    slogan: 'Personal finance reimagined with AI',
    url: 'https://walletguide.com'
  },
  {
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'wallmine',
    languages: ['English'],
    name: 'wallmine',
    note: 'wallmine was discontinued in 2024',
    origin: 'CZ',
    pricingPerYear: '$600',
    slogan: 'Make Smarter Investments'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    founded: 2020,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'wallstreetzen',
    name: 'WallStreetZen',
    origin: 'HK',
    platforms: ['WEB'],
    pricingPerYear: '$234',
    slogan: 'Stock market analysis for the serious part-time investor',
    url: 'https://www.wallstreetzen.com'
  },
  {
    categories: ['FAMILY_OFFICE', 'WEALTH_MANAGEMENT'],
    founded: 2015,
    hasSelfHostingAbility: false,
    key: 'wealtharc',
    name: 'WealthArc',
    origin: 'CH',
    platforms: ['WEB'],
    slogan: 'Manage wealth data more efficiently',
    url: 'https://www.wealtharc.com'
  },
  {
    categories: ['FAMILY_OFFICE', 'WEALTH_MANAGEMENT'],
    founded: 2019,
    hasFreePlan: false,
    key: 'wealthbrain',
    languages: ['English'],
    name: 'Wealthbrain',
    origin: 'AE',
    platforms: ['WEB'],
    slogan: 'Portfolio Management System',
    url: 'https://wealthbrain.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2024,
    hasSelfHostingAbility: true,
    isArchived: true,
    isOpenSource: true,
    key: 'wealthfolio',
    languages: ['English'],
    name: 'Wealthfolio',
    origin: 'CA',
    platforms: ['IOS', 'LINUX', 'MACOS', 'WEB', 'WINDOWS'],
    slogan: 'Open-Source, Offline & Private Portfolio Tracker',
    url: 'https://wealthfolio.app'
  },
  {
    categories: ['NET_WORTH_TRACKING'],
    founded: 2015,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    key: 'wealthica',
    languages: ['English', 'Français'],
    name: 'Wealthica',
    origin: 'CA',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$50',
    slogan: 'See all your investments in one place',
    url: 'https://wealthica.com'
  },
  {
    categories: ['BUDGETING'],
    founded: 2018,
    hasFreePlan: true,
    key: 'wealthposition',
    name: 'WealthPosition',
    platforms: ['WEB'],
    pricingPerYear: '$60',
    slogan: 'Personal Finance & Budgeting App',
    url: 'https://www.wealthposition.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2018,
    hasSelfHostingAbility: false,
    key: 'wealthy-tracker',
    languages: ['English'],
    name: 'Wealthy Tracker',
    origin: 'IN',
    platforms: ['WEB'],
    slogan: 'One app to manage all your investments',
    url: 'https://www.wealthy.in/tracker'
  },
  {
    categories: ['STOCK_TRACKING'],
    key: 'whal',
    name: 'Whal',
    origin: 'US',
    slogan: 'Manage your investments in one place'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    key: 'wisesheets',
    name: 'Wisesheets',
    slogan: 'The Ultimate Spreadsheet Add-On for Stock Investors',
    url: 'https://www.wisesheets.io'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'WEALTH_MANAGEMENT'],
    key: 'ycharts',
    name: 'YCharts',
    slogan: 'Financial Research and Proposal Platform',
    url: 'https://ycharts.com'
  },
  {
    categories: ['STOCK_TRACKING'],
    founded: 2021,
    hasFreePlan: true,
    hasSelfHostingAbility: false,
    isArchived: true,
    key: 'yeekatee',
    languages: ['Deutsch', 'English', 'Español', 'Français', 'Italiano'],
    name: 'yeekatee',
    note: 'yeekatee was discontinued in 2024',
    origin: 'CH',
    regions: ['Global'],
    slogan: 'Connect. Share. Invest.'
  },
  {
    categories: ['BUDGETING'],
    founded: 2004,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'ynab',
    name: 'YNAB (You Need a Budget)',
    origin: 'US',
    platforms: ['ANDROID', 'IOS', 'WEB'],
    pricingPerYear: '$109',
    slogan: 'Change Your Relationship With Money',
    url: 'https://www.ynab.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH'],
    hasFreePlan: true,
    key: 'zacks',
    name: 'Zacks',
    slogan: 'Stock Research, Analysis, & Recommendations',
    url: 'https://www.zacks.com'
  },
  {
    categories: ['CRYPTOCURRENCY', 'STOCK_TRACKING'],
    key: 'zenvesto',
    name: 'Zenvesto',
    slogan: 'Smart Investment Portfolio Tracker',
    url: 'https://zenvesto.com'
  },
  {
    categories: ['INVESTMENT_RESEARCH', 'STOCK_TRACKING'],
    founded: 2019,
    hasFreePlan: false,
    hasSelfHostingAbility: false,
    key: 'ziggma',
    name: 'Ziggma',
    origin: 'US',
    platforms: ['WEB'],
    pricingPerYear: '$84',
    slogan: 'Your solution for investing success',
    url: 'https://ziggma.com'
  }
];
