export enum EntityType {
  INDIVIDUAL = 'INDIVIDUAL',
  TRUST = 'TRUST',
  LLC = 'LLC',
  LP = 'LP',
  CORPORATION = 'CORPORATION',
  FOUNDATION = 'FOUNDATION',
  ESTATE = 'ESTATE'
}

export enum PartnershipType {
  LP = 'LP',
  GP = 'GP',
  LLC = 'LLC',
  JOINT_VENTURE = 'JOINT_VENTURE',
  FUND = 'FUND'
}

export enum DistributionType {
  INCOME = 'INCOME',
  RETURN_OF_CAPITAL = 'RETURN_OF_CAPITAL',
  CAPITAL_GAIN = 'CAPITAL_GAIN',
  GUARANTEED_PAYMENT = 'GUARANTEED_PAYMENT',
  DIVIDEND = 'DIVIDEND',
  INTEREST = 'INTEREST'
}

export enum KDocumentType {
  K1 = 'K1',
  K3 = 'K3'
}

export enum KDocumentStatus {
  DRAFT = 'DRAFT',
  ESTIMATED = 'ESTIMATED',
  FINAL = 'FINAL'
}

export enum FamilyOfficeAssetType {
  PUBLIC_EQUITY = 'PUBLIC_EQUITY',
  PRIVATE_EQUITY = 'PRIVATE_EQUITY',
  REAL_ESTATE = 'REAL_ESTATE',
  HEDGE_FUND = 'HEDGE_FUND',
  VENTURE_CAPITAL = 'VENTURE_CAPITAL',
  FIXED_INCOME = 'FIXED_INCOME',
  COMMODITY = 'COMMODITY',
  ART_COLLECTIBLE = 'ART_COLLECTIBLE',
  CRYPTOCURRENCY = 'CRYPTOCURRENCY',
  CASH = 'CASH',
  OTHER = 'OTHER'
}

export enum ValuationSource {
  APPRAISAL = 'APPRAISAL',
  MARKET = 'MARKET',
  MANUAL = 'MANUAL',
  NAV_STATEMENT = 'NAV_STATEMENT',
  FUND_ADMIN = 'FUND_ADMIN'
}

export enum DocumentType {
  K1 = 'K1',
  K3 = 'K3',
  CAPITAL_CALL = 'CAPITAL_CALL',
  DISTRIBUTION_NOTICE = 'DISTRIBUTION_NOTICE',
  NAV_STATEMENT = 'NAV_STATEMENT',
  APPRAISAL = 'APPRAISAL',
  TAX_RETURN = 'TAX_RETURN',
  SUBSCRIPTION_AGREEMENT = 'SUBSCRIPTION_AGREEMENT',
  OTHER = 'OTHER'
}
